### ISSUE TITLE
Flask guide needs to be updated

### ISSUE THREAD

**Issue by johngouf** [supertokens/supertokens-python#106]
Hi everyone!

Was following the guide in https://supertokens.com/docs/flask/usage/setup but I realized that it's deprecated as the example here https://github.com/supertokens/supertokens-python/tree/master/examples/with-flask/with-thirdpartyemailpassword uses supertokens-python and not supertokens-flask package.
Is there a version of the guide reflecting the latest changes?

**Comment by rishabhpoddar** [comment]
Yes. All [these guides](https://supertokens.com/docs/guides) use supertokens-python. Furthermore, the API ref for supertokens-python is https://supertokens.io/docs/python

**Comment by rishabhpoddar** [comment]
Closing this issue for now.

**Comment by johngouf** [comment]
perfect, thanks for the pointer @rishabhpoddar !
