### ISSUE TITLE
No verification email sent

### ISSUE THREAD

**Issue by johngouf** [supertokens/supertokens-python#110]
Hi there,

I am using the sample of this repo https://github.com/supertokens/supertokens-python/tree/master/examples/with-flask/with-thirdpartyemailpassword with the react frontend.
Everything works without a problem for the social logins. However when I try to sign up using an email I get a notification that my email needs to be verified, but I didn't receive anything (checked spam folder as well) and can't see any error on the flask side.
Any hints would be greatly appreciated!

**Comment by rishabhpoddar** [comment]
hey @johngouf i just tried the flow myself. I got the email verification email.

One thing you could do is to [provide the email verification callback](https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/email-verification/email-verification-email) yourself in the backend code and print something to see if it comes there. If it does, it means that the email was being sent and for some other reason not reaching you (note that this callback is for if you want to send the email yourself, so if you provide it and do a `print` in it, then the email won't be sent).

If you do not see the print output, it means that the email was never sent and that could indicate some bug somewhere. Do let me know.

**Comment by johngouf** [comment]
Hi @rishabhpoddar thanks for the suggestion,
Indeed when I add:
```
async def create_and_send_custom_email(user: User, email_verification_url: str, user_context: Dict[str, Any]):
    print("create and send custom email")
    print(user,email_verification_url,user_context)
    pass # TODO
```
and configure:
```
email_verification_feature=
            thirdpartyemailpassword.InputEmailVerificationConfig(
                create_and_send_custom_email=create_and_send_custom_email),
```
it gets printed out. However when I take it out nothing happens with no errors

**Comment by rishabhpoddar** [comment]
hey! I have sent you an email regarding this issue - maybe we can get on a quick call to debug this issue.

I tried sending a verification email to your email from [our demo app](https://thirdpartyemailpassword.demo.supertokens.io/) and i think that got sent.

**Comment by rishabhpoddar** [comment]
From before I sent you an email using the demo app, there were no emails sent to your ID from our email service. This means that the SDK probably failed to contact our servers when requesting to send the email. Is there any local setup you have that would prevent a call to `https://api.supertokens.io`?

The reason you don't see any errors is that the SDK is setup to ignore errors that happen when contacting our servers to send the email since it's only meant for development / demo purposes. For production, you should implement this callback and handle sending emails yourself anyway (as of v0.6.2 of the python SDK).

**Comment by johngouf** [comment]
Hi @rishabhpoddar 

thanks so much for investigating this! I did indeed receive the verification email you sent. Something must be happening on my end. It makes sense not to spend too much time on it since as you said, I would need to implement my own callback.

**Comment by rishabhpoddar** [comment]
I'm closing this issue since it doesn't seem like a problem on our end.

**Comment by rishabhpoddar** [comment]
hey @johngouf it turns out that there was a bug in the SDK which prevented the email verification email from being sent if testing mode was NOT on. (It should have been the other way around). We have fixed this issue in the the python SDK version >= v0.6.4.

**Comment by yiannis-zen** [comment]
Hey @rishabhpoddar thanks for figuring out what was wrong!
