### ISSUE TITLE
Missing user parameter for email_delivery config

### ISSUE THREAD

**Issue by Luxaaa** [supertokens/supertokens-python#217]
Hi,
If I want to configure my own smtp server for email sending (email confirmation / password change), there is no way to specify a username for my server if the username is different from the sender email id.
To use my smtp, I have to implement email sending myself. Would be nice to have a user parameter.

**Comment by rishabhpoddar** [comment]
Agreed. We will work on this soon

**Comment by bert2002** [comment]
That would be great since its a important setting for any bigger deployments.

**Comment by andreipopovici** [comment]
Adding to this request so we can reduce the load on the Supertokens email servers by using our own 😅

Relevant line is https://github.com/supertokens/supertokens-python/blob/382d417f8d1e095746dafdbb409d939686843def/supertokens_python/ingredients/emaildelivery/services/smtp.py#L62

**Comment by rishabhpoddar** [comment]
this has now been added in version >= 0.11.1
