### ISSUE TITLE
Add Twitter as ThirdParty EmailPassword Provider

### ISSUE THREAD

**Issue by Zaker237** [supertokens/supertokens-python#219]
Hi Everyone,
i was try to use super tokens python client for third party authentication in my app an figure out the twitter is right now not yet included as third party authentication. I think it can be helpful to also have it.

**Comment by rishabhpoddar** [comment]
Twitter uses OAuth 1.0, and we don't support that yet - that's why it's not included in the list. They do have Oauth 2.0, but the access is very limited.
