### ISSUE TITLE
get_session seams to call the supertokens core

### ISSUE THREAD

**Issue by Luxaaa** [supertokens/supertokens-python#222]
Hello,
The `get_vession` function seams to call the supertokens core. So the session verification in < 1ms like described in the docs is not possible. I am using the latest verion of the python sdk (currently 0.10.4).
Here is my code:
```python
a = time()
session = await original_get_session(request, anti_csrf_check, session_required, user_context)
b = time()
print('time', b - a)
```
The difference between b and a is abount 0.3s (might be better with better inet connection). But the get_sesion should not depend on the network.

(access_token_blacklisting is set to false)

**Comment by rishabhpoddar** [comment]
Thanks for the issue @Luxaaa . `get_session` should only be calling the core once post session refreshing and not always. So most of the time, it should be stateless and very quick. We will investigate why it's querying the core each time.

**Comment by KShivendu** [comment]
Hey @Luxaaa, thanks for reporting this issue. I tried replicating your issue and found that 0.3s happens only for the first call to get_session (as mentioned y @rishabhpoddar). Rest of the calls take 0.01 to 0.03 s.

Ca you please try calling it for the second time and let me know if the issue still persists? :)

**Comment by rishabhpoddar** [comment]
@KShivendu the core being self hosted or not shouldn't really matter post the first verification - cause `get_session` doesn't contact the core at all the second, third.. times.

**Comment by Luxaaa** [comment]
@KShivendu It takes 0.3s every time i am calling `get_session`.
Here is the complete file of my session override:
```python
from supertokens_python.framework.fastapi.fastapi_request import BaseRequest
from supertokens_python.recipe.session.interfaces import RecipeInterface
from config2 import SUPERTOKENS_HEADER
from starlette.requests import Request
from time import time


def _update_headers_in_request(rq: BaseRequest):
    rq: Request = rq.request
    new_headers = rq.headers.mutablecopy()
    if st_cookie := rq.headers.get(SUPERTOKENS_HEADER):
        current = rq.headers.get('cookie', '')
        new_headers['cookie'] = f'f{current}; {st_cookie}'
    rq._headers = new_headers
    rq.scope.update(headers=rq.headers.raw)


def override_session_functions(oi: RecipeInterface):
    original_create_new_session = oi.create_new_session
    original_refresh_session = oi.refresh_session
    original_get_session = oi.get_session

    async def create_new_session(request, user_id, access_token_payload, session_data, user_context):
        _update_headers_in_request(request)
        session = await original_create_new_session(request, user_id, access_token_payload, session_data, user_context)
        return session

    async def refresh_session(request, user_context):
        _update_headers_in_request(request)
        session = await original_refresh_session(request, user_context)
        return session

    async def get_session(request, anti_csrf_check, session_required, user_context):
        _update_headers_in_request(request)
        a = time()
        session = await original_get_session(request, anti_csrf_check, session_required, user_context)
        b = time()
        print('time', b - a)
        a = time()
        session = await original_get_session(request, anti_csrf_check, session_required, user_context)
        b = time()
        print('time', b - a)

        return session

    oi.create_new_session = create_new_session
    oi.refresh_session = refresh_session
    oi.get_session = get_session

    return oi

```

As you can see, i am calling `get_session` 2 times and both calls take about 0.3s.

**Comment by rishabhpoddar** [comment]
@Luxaaa get_session reads from the request object, and calling it twice on the same request object is the same as calling it just once. Do you see that it takes 0.3 secs for consecutive requests as well?

**Comment by Luxaaa** [comment]
@rishabhpoddar Yes. Each of my api requests spends 0.3s on get_session

**Comment by KShivendu** [comment]
Hey @Luxaaa, can you please try and tell how long this one takes

```python
from supertokens_python.recipe.session.syncio import get_session

@fastapi_app.get("/secure")
def secure_api(request: Request):
    print("Secure api called")
    a = perf_counter_ns()
    s = get_session(request)
    b = perf_counter_ns()
    print("/secure: get_session", (b - a) / 1000_000)
```

**Comment by Luxaaa** [comment]
@KShivendu 
```pytho
Secure api called
time 0.49855828285217285
time 0.3567025661468506
/secure: get_session 855.64369
INFO:     127.0.0.1:43364 - "GET /secure HTTP/1.1" 200 OK
Secure api called
time 0.30037879943847656
time 0.29277682304382324
/secure: get_session 593.331677
INFO:     127.0.0.1:43372 - "GET /secure HTTP/1.1" 200 OK
```
Called it 2 times

**Comment by rishabhpoddar** [comment]
@Luxaaa can you try these without the custom overrides you added and then see how long they take?

**Comment by Luxaaa** [comment]
@rishabhpoddar 
```python
Secure api called
/secure: get_session 338.008723
INFO:     127.0.0.1:50302 - "GET /secure HTTP/1.1" 200 OK
Secure api called
/secure: get_session 304.727049
INFO:     127.0.0.1:50308 - "GET /secure HTTP/1.1" 200 OK
```

**Comment by rishabhpoddar** [comment]
Hmmm. Can we get on a debugging call for this? Will be easier to figure out what's going wrong. You can pick a time you like here https://supertokens.com/call-user

**Comment by Luxaaa** [comment]
@rishabhpoddar 
After hours of investigating i fixed it. I simply upgraded all my packages. I dont know which package caused the issue but now it works like expected. 
Thanks for all your help.

**Comment by rishabhpoddar** [comment]
Hmm. Alright! Good to know that it worked. Please feel free to reopen this issue if needed.
