### ISSUE TITLE
FastAPI root_path is duplicated in request

### ISSUE THREAD

**Issue by bert2002** [supertokens/supertokens-python#230]
Hi,
it seems that when `root_path` is set in `FastAPI()` it gets added twice to the request path. E.g.:

```
app = FastAPI(
  root_path="/api",
)
```

and the init configuration for supertokens:
```
  app_info=InputAppInfo(
    api_domain="http://localhost:8000",
    website_domain="http://localhost:8000",
    api_base_path="/auth",
    website_base_path="/auth"
  ),
```
and when we try to access the endpoint:
```
# curl http://localhost:8000/api/auth/signin -X POST
{"detail":"Not Found"}
```
and this results in a double `/api/api/`
```
api_1              | DEBUG:     {"t": "2022-09-24T05:10:45.061Z", "sdkVer": "0.11.0", "message": "middleware: Not handling because request path did not start with config path. Request path: /api/api/auth/signin", "file": "supertokens.py:543"} (line:543)
```
This can be reproduced with any `root_path` path set.

Thanks,
bert

**Comment by rishabhpoddar** [comment]
This issue should be fixed in python SDK version >= 0.11.2. Please feel free to reopen in case the issue persists.
