### ISSUE TITLE
Validating roles

### ISSUE THREAD

**Issue by bert2002** [supertokens/supertokens-python#232]
Hi,
on the page about [Protecting API routes](https://supertokens.com/docs/userroles/protecting-routes) it says following:
```
Validate that the roles/permissions saved in the access token payload have the appropriate value
```
and when we look at the code at:
```
verify_session(
            # We add the UserRoleClaim's includes validator
            override_global_claim_validators=lambda global_validators, session, user_context: global_validators + \
            [UserRoleClaim.validators.includes("admin")]
        )
```
I didnt had a deeper look at `verify_session`, but it sounds in the description that only the claim of the access token payload gets verified against the code (e.g. `UserRoleClaim.validators.includes("admin")`) and not what is stored in the database? Does the claim gets verified against the database entries?

Please let me know if I am wrong,

bert

**Comment by rishabhpoddar** [comment]
Hey! They get refreshed from the db every 5 mins by default. But you can make it check the db everytime as well if you passe `max_age_in_seconds` arg to the `includes` function:

```
UserRoleClaim.validators.includes(val="admin", max_age_in_seconds=0)
```
