### ISSUE TITLE
Unable to paginate users

### ISSUE THREAD

**Issue by ShorthairBerry** [supertokens/supertokens-python#248]
While using the get_users_newest_first() method it returns an Attribute error stating 'str' object has no attribute 'values'

views.py file
```python
from rest_framework.response import Response
from rest_framework.decorators import api_view
from supertokens_python.syncio import get_users_newest_first
from .serializers import GetUserSerializer


@api_view(['GET'])
def get_users(request):
    firstguys = get_users_newest_first()
    serializer = GetUserSerializer(firstguys)
    return Response(serializer.data)
```

serializers.py file
```python
from attr import fields
from rest_framework import serializers


class GetUserSerializer(serializers.Serializer):
    fields = '__all__'
```

**Comment by KShivendu** [comment]
Hey, `fields = '__all__'` works only with Django Models (that too only with serializers inherited from `serializers.ModelSerializer`) 

So you should try this instead:
```python
@api_view(['GET'])
def get_users(request):
    firstguys = get_users_newest_first()
    serializer = GetUserSerializer(firstguys.users, many=True) # note this line
    return Response(serializer.data)

```

```python
class GetUserSerializer(serializers.Serializer):
    user_id = serializers.CharField()
    email = serializers.EmailField()
    recipe_id = serializers.CharField()
    time_joined = serializers.IntegerField()
```

Also, this is a custom API View, so there will be more steps involved for integrating the default pagination into this. I'll share snippets for that in a while.

**Comment by KShivendu** [comment]
Here's what you can try to make it work with your default drf paginator: 

views.py:
```python
from rest_framework.decorators import api_view
from supertokens_python.syncio import get_users_newest_first

from rest_framework.settings import api_settings

@api_view(["GET"])
def get_users(request):
    paginator = api_settings.DEFAULT_PAGINATION_CLASS()
    firstguys = get_users_newest_first()

    page = paginator.paginate_queryset(firstguys.users, request)
    serializer = GetUserSerializer(page, many=True)

    return paginator.get_paginated_response(serializer.data)
```

settings.py:
```python
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}
```

**Comment by ShorthairBerry** [comment]
Thanks very much for your help, it worked!! Sent from Mail for Windows From: Kumar ShivenduSent: 21 October 2022 08:43To: supertokens/supertokens-pythonCc: ShorthairBerry; AuthorSubject: Re: [supertokens/supertokens-python] Unable to paginate users (Issue #248) Here's what you can try to make it work with your default drf paginator:views.py:from rest_framework.decorators import api_viewfrom supertokens_python.syncio import get_users_newest_first from rest_framework.settings import ***@***.***_view(["GET"])def get_users(request):    paginator = api_settings.DEFAULT_PAGINATION_CLASS()    firstguys = get_users_newest_first()     page = paginator.paginate_queryset(firstguys.users, request)    serializer = GetUserSerializer(page, many=True)     return paginator.get_paginated_response(serializer.data)settings.py:REST_FRAMEWORK = {    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",    "PAGE_SIZE": 10,}—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by rishabhpoddar** [comment]
Closing this issue since it seems to be resolved.
