### ISSUE TITLE
Mention require `supertokens-auth-react` >= 0.31.0 for `supertokens-python` >= 0.12.0

### ISSUE THREAD

**Issue by CyberneticTurtle** [supertokens/supertokens-python#285]
Firstly, thank you for your work on SuperTokens.

I previously had the dev environment for SuperTokens working (i.e. using the development credentials) on v0.11.13 using the `thirdpartypasswordless` recipe, however after updating to v0.12.1, the dev environment consumes the OTP/magic link but does not actually authenticate and redirect to the website.

After some debugging, I found that what worked was either downgrading `supertokens-python` to v0.11.13 to match `supertokens-auth-react` v0.30.2 OR to upgrade `supertokens-auth-react` to v0.31.1 while keeping `supertokens-python` at v0.12.1. It seems like the incompatibilities come from a new way to do authentication using the header.

I think it would be prudent to mention incompatibilities between frontend/backend versions so that users can migrate when they have time.

**Comment by rishabhpoddar** [comment]
Hey @CyberneticTurtle We do mention it here:
- In the changelog: https://github.com/supertokens/supertokens-python/blob/master/CHANGELOG.md
- In our compatibility web page: https://supertokens.com/docs/thirdpartypasswordless/compatibility-table

**Comment by CyberneticTurtle** [comment]
Ah right. Apologies, I missed that. I was looking at the [releases](https://github.com/supertokens/supertokens-python/releases) page instead.
