### ISSUE TITLE
Failed to build a backend on Deta Space following the Passwordless Recipe

### ISSUE THREAD

**Issue by kumkee** [supertokens/supertokens-python#296]
I followed the [Passwordless Recipe](https://supertokens.com/docs/passwordless/custom-ui/init/backend) from Supertokens documentation and created an [experiment](https://github.com/kumkee/SupertokensElm) to build an SuperTokens-core-connected backend on [Deta Space](https://deta.space/). I reached Step 4: User management dashboard but failed to get the enter API screen.

While the dashboard works perfectly fine with local `uvicorn` or `gunicorn` servers, I encountered errors when deploying it on Deta Space. Deta Space has its [own global ASGI/WSGI server](https://files.deta.dev/opt/python/detalib/), which might be causing the issue.

I have deployed the code on Deta Space, and you can check the live UM dashboard on this URL: https://stokensdemo-1-z8458742.deta.app/auth/dashboard. However, it returns an error message.

# Steps to reproduce

1. Follow the Passwordless Recipe from Supertokens documentation to create a Supertokens passwordless custom UI, or directly clone [my repo from here](https://github.com/kumkee/SupertokensElm).
2. Deploy the code on Deta Space.
3. Try to access the User management dashboard on Deta Space.
4. Observe the error message.

# Expected result

The User management dashboard should work without any errors on Deta Space.

# Actual result

The User management dashboard returns the error message listed at the end of the post.

# Additional information

- Deta Space doesn't use a server like `uvicorn` but has its [own global server](https://files.deta.dev/opt/python/detalib/), which might be causing the issue.
- Supertokens documentation doesn't provide any information on how to deploy the backend on Deta Space or similar serverless infrastructure.
- The live UM dashboard can be accessed on this URL: https://stokensdemo-1-z8458742.deta.app/auth/dashboard.
- My code is listed in my [SupertokensElm repo](https://github.com/kumkee/SupertokensElm) under the [backend directory](https://github.com/kumkee/SupertokensElm/tree/supertokens/backend).

# Error Message

```
Error Type:
RuntimeError

Error Message:
There is no current event loop in thread 'MainThread'.

Logs:
time="2023-03-12T16:53:08Z" level=info msg="serving logs listener on sandbox.localdomain:1234" agent=logsApiAgent
TELEMETRY	Name: telemetry-extension	State: Subscribed	Types: [Function]
[WARNING]	2023-03-12T16:53:10.687Z		unable to cache publicsuffix.org-tlds.{'urls': ('https://publicsuffix.org/list/public_suffix_list.dat', 'https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat'), 'fallback_to_snapshot': True} in /opt/python/tldextract/.suffix_cache/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json. This could refresh the Public Suffix List over HTTP every app startup. Construct your `TLDExtract` with a writable `cache_dir` or set `cache_dir=False` to silence this warning. [Errno 30] Read-only file system: '/opt/python/tldextract/.suffix_cache'
Stack Trace:
  File "/opt/python/detalib/debugger.py", line 131, in wrap
    return func(event, context)

  File "/var/task/_entry.py", line 15, in handler
    return handle(event, main)

  File "/opt/python/detalib/handler.py", line 25, in handle
    return handlers.handle_bare_asgi(event, main, context)

  File "/opt/python/detalib/handlers.py", line 21, in handle_bare_asgi
    return Asgi(main.app, enable_lifespan=False)(event, context)

  File "/opt/python/detalib/adapters/asgi/adapter.py", line 57, in __call__
    raise exc

  File "/opt/python/detalib/adapters/asgi/adapter.py", line 55, in __call__
    response = self.handler(event, context)

  File "/opt/python/detalib/adapters/asgi/adapter.py", line 61, in handler
    response = self.handle_http(event, context)

  File "/opt/python/detalib/adapters/asgi/adapter.py", line 105, in handle_http
    asgi_cycle = ASGIHTTPCycle(scope, is_binary=is_binary, logger=self.logger)

  File "", line 10, in __init__

  File "/opt/python/detalib/adapters/asgi/protocols/http.py", line 35, in __post_init__
    self.loop = asyncio.get_event_loop()

  File "/var/lang/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
```

**Comment by KShivendu** [comment]
Hi @kumkee, try to see if sync FastAPI functions work in Deta Space. 

Also, It should be possible to use uvicorn using the `custom` engine. I think `run` and `commands` parameters in the Spacefile can solve your problem. Checkout https://deta.space/docs/en/quickstart-guides/go and the one for Rust :)

**Comment by kumkee** [comment]
> Hi @kumkee, try to see if sync FastAPI functions work in Deta Space.
> 
> Also, It should be possible to use uvicorn using the `custom` engine. I think `run` and `commands` parameters in the Spacefile can solve your problem. Checkout https://deta.space/docs/en/quickstart-guides/go and the one for Rust :)

Thank you, @KShivendu. I am trying the second solution you suggested. It complains `uvicorn: command not found`.
I'll try using virtual env under custom engine next.

**Comment by kumkee** [comment]
> Also, for uvicorn maybe try `python3.9 -m uvicorn ...`

I've tried both relative and [absolute paths to python3.9](https://github.com/kumkee/SupertokensElm/blob/68104de0c923f2a752b75a7bda731fa9ff87c175/Spacefile), but no luck.
```
/var/task/run.sh: line 4: /usr/bin/python3.9: No such file or directory
```

**Comment by KShivendu** [comment]
You can also try using `engine: python3.9` along with `commands` and `run`.

Because when I tried it yesterday, it looked like I was still able to add the `commands` config and they were working. However, I'm not sure about the `run` config.

**Comment by kumkee** [comment]
> 
> ### Next
> I'll try next finding out where `python3.9` is on a FastAPI response.

It turns out that It doesn't even have a `which` command under a custom engine.
Under `python3.9` engine using `shutil.which`, python executable is in `/var/lang/bin/python3.9` so it seams they are isolating the runtime environment from the build one.

**Comment by abdelhai** [comment]
hi, sorry for the late response. we don't support custom `run` commands for python yet but this will be coming soon. right now, we just expect an ASGI/WSGI with the name of `app` in the entryfile `main.py` and we try to run it. the runner is buggy in some cases and this is why we will be replacing it soon.

on the first scan, I'm not sure what's causing the problem. if you reopen the issue, we're happy to investigate further.

**Comment by kumkee** [comment]
> if you reopen the issue, we're happy to investigate further.

Yes please. I will reopen the issue.

**Comment by KShivendu** [comment]
Hmm. I guess then we don't need to modify anything in the supertokens python SDK. So I'm closing this issue. Feel free to contact us if you come across another issue. You can also join our discord server for such discussions. 

Thanks @abdelhai for taking care of the issue :)

**Comment by kumkee** [comment]
For your information, the problem has been solved there in Deta. 
Thank you, @KShivendu and the rest of the SuperTokens team.
