### ISSUE TITLE
Upgrade cryptography library

### ISSUE THREAD

**Issue by atambo** [supertokens/supertokens-python#351]
supertokens-python is currently pinning the cryptography version to 35-36: https://github.com/supertokens/supertokens-python/blob/master/setup.py#L109

It would be awesome if we could start using newer versions of the cryptography library. I’m running into compatibility issues with other libraries that require newer version of the cryptography library.

https://cryptography.io/en/latest/

**Comment by rishabhpoddar** [comment]
We shall have a look at this sometime in the next 1-2 weeks.

**Comment by KShivendu** [comment]
Hi @atambo, thanks for raising this issue. Can you specifically tell us what version conflicts are you facing. That will help us decide the new constraints?

**Comment by atambo** [comment]
I have some libraries that require a newer versions of `pyopenssl`: https://www.pyopenssl.org/en/latest/changelog.html#id22
So I think the minimum version of the `cryptography` library that the `pyopenssl` library supports is 38 and the maximum is supports is 41.

**Comment by rishabhpoddar** [comment]
We have released a new version of the python SDK with the relaxed constraint (version >= 0.14.5). Closing this for now, but feel free to reopen in case the issue persists.
