### ISSUE TITLE
Regression: core version is not compatible with this FastAPI SDK

### ISSUE THREAD

**Issue by igoose1** [supertokens/supertokens-python#361]
I needed `verify_session(check_database=...)` for FastAPI. That fix was added in 81d4661b1a98fcfed3714042bd8fef0c733b31a9 so I upgraded supertokens to 0.14.6. After that the project fails with incompatibility:

```
supertokens_python.exceptions.GeneralError: The running SuperTokens core version is not compatible with this FastAPI SDK. Please visit https://supertokens.io/docs/community/compatibility-table to find the right versions
```

These are compatible versions:
* `supertokens-python==0.12.9` (no check_database supported)
* `fastapi==0.89.1`

These are incompatible versions:
* `supertokens-python==0.14.6`
* `fastapi==0.89.1`

I tried to upgrade and downgrade FastAPI few times. Even `fastapi==0.98.0` failed. It's weird because in CI it worked (?): https://app.circleci.com/pipelines/github/supertokens/supertokens-python/2271/workflows/d8d111b9-69c2-417b-80aa-879193ed5eca/jobs/2974.

FYI: A web-link in exception seems useless. I clicked a form and didn't find anything related to FastAPI. Finally I needed to open source code to debug and to file an issue finally as I didn't succeed. Probably, "FastAPI SDK" must be reworded to "supertokens-python" here.

**Comment by igoose1** [comment]
That issue was wrong. I didn't notice word "core" in an exception message. Fix was to upgrade local supertokens core.

Message in an exception can be misleading with "FastAPI". I'd still suggest to not point on a framework and use general "supertokens-python".

**Comment by igoose1** [comment]
Well, probably that's fully my inattention :-)

**Comment by rishabhpoddar** [comment]
Thanks for this issue. We will still change the error message in the SDK since it should not say fastAPI.
