### ISSUE TITLE
Unable to set cookie_same_site in config of session recipe

### ISSUE THREAD

**Issue by acontass** [supertokens/supertokens-python#42]
As the allowed values are `{'Strict', 'Lax', 'None'}` It seems to be impossible to `set cookie_same_site` value in config of the session recipe due to `same_site.lower()` called on `normalise_same_site`:

```python
def normalise_same_site(same_site: str) -> str:
    same_site = same_site.strip()
    same_site = same_site.lower() # This line should be removed to fix it.
    allowed_values = {'Strict', 'Lax', 'None'}
    if same_site not in allowed_values:
        raise Exception(
            'cookie same site must be one of "Strict", "Lax", or "None"')
    return same_site
```

I just try to create a PR to fix it but it seems I'm not allowed to do that.

Can you fix it please ?

**Comment by rishabhpoddar** [comment]
This has been fixed in v0.2.0.
