### ISSUE TITLE
Update aiosmtplib

### ISSUE THREAD

**Issue by andreipopovici** [supertokens/supertokens-python#481]
`aiosmtplib` is pinned to `"aiosmtplib==1.1.6"`, but I would like to use something like https://sabuhish.github.io/fastapi-mail which requires a newer version. `poetry` cannot install `fastapi-mail` due to the lower version required by `supertokens-python`.

The [v3.0.1 docs ](https://aiosmtplib.readthedocs.io/en/stable/reference.html#) don't seem to have any breaking changes, when compared to usage in https://github.com/supertokens/supertokens-python/blob/master/supertokens_python/ingredients/emaildelivery/services/smtp.py, so a simple version bump might work.

Is this something I could help with?

**Comment by rishabhpoddar** [comment]
We have fixed this in supertokens-python sdk version >= 0.18.10
