### ISSUE TITLE
Fix example folder structure

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-python#57]
Inside example/fastapi, have a folder for each type of app:
- with-thirdparty
- with-thirdpartyemailpassword

Likewise for other frameworks.

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya as discussed, you need to also push the OAuth creds to github (the ones in the docs)

**Comment by bhumilsarvaiya** [comment]
Added for the existing examples
