### ISSUE TITLE
Bug in User Pagination [Python backend] [supertokens-python = "^0.5.2"]

### ISSUE THREAD

**Issue by fermenen** [supertokens/supertokens-python#95]
**Bug in User Pagination** 
Count works correctly!

- Python backend
- supertokens-python = "^0.5.2"

supertokens_python.exceptions.GeneralError: SuperTokens core threw an error for a GET request to path: /users with status code: 400 and message: invalid pagination token

![Captura de pantalla de 2022-03-25 11-11-26](https://user-images.githubusercontent.com/32095133/160101705-bfcd7095-7066-401e-8493-3fe9db2f8e4b.png)
![Captura de pantalla de 2022-03-25 11-12-06](https://user-images.githubusercontent.com/32095133/160101709-3ee9bddf-c713-41dc-9e3d-4767bbc4607a.png)

**Comment by rishabhpoddar** [comment]
This has been fixed in the latest version v0.5.3. Please feel free to reopen in case the error persists.

**Comment by rishabhpoddar** [comment]
hey @fermenen did you by any chance access the dev env db and remove a few users from the emailpassword_users table?
